### ISSUE TITLE
Issues to be dealt with

### ISSUE THREAD

**Issue by metaphori** [metaphori/protelis-to-kotlin-doc#2]
@DanySK here are some issues to be dealt with regarding Protelis to Kotlin conversion:

- Please tag Matteo in order to determine what is the semantics of the following: `@return          [[num|T,T']], [[imRoot()|noParent()|f(parent), g(value)]]`
  * Meaning of the pipe (alternative?)
  * Meaning of `[...]` (tuple?)
  * Meaning of the apparent function calls (anyway, they appear in the textual "description", not in the typing place)
```
/**
 * Find the parents of the current device following the decrease in
 * potential.
 *
 * @param potential num, potential
 * @param f         (ExecutionContext) -> T, what to do with the parent
 * @param g         (T') -> T', what to do with the value
 * @param local     T', local value
 * @return          [[num|T,T']], [[imRoot()|noParent()|f(parent), g(value)]]
 * @see imRoot, noParent
 */
public def getParents(potential, f, g, local, default) {
    getParentsExtended(potential, identity, f, g, local, default)
}
```
- How to deal with `@param f         (ExecutionContext) -> T, what to do with the parent`: is `ExecutionContext` a protelis type? If I just take it along, kotlinc doesn't compile. Do I need to add an empty interface `ExecutionContext` in the kotlin file?

**Comment by DanySK** [comment]
@w4bo, we need an explanation from you :)

**Comment by w4bo** [comment]
```
/**
 * Find the parents of the current device following the decrease in
 * potential.
 *
 * @param potential num, potential    // This a numeric value along a gradient (e.g., G)
 * @param f         (ExecutionContext) -> T, what to do with the parent    // f takes (Protelis/Java) an ExecutionContext as a parameter and returns a value of type T
 * @param g         (T') -> T', what to do with the value    // g takes a parameter of type T', and returns a value of type T
 * @param local     T', local value    // local is a value of type T'
 * @return          [[num|T,T']], [[imRoot()|noParent()|f(parent), g(value)]]    // this a tuple of two tuples
 * @see imRoot, noParent    // these are placeholders for the default values imported by the Proto implementation of C, I wrapped them into functions to make them clearer to the reader
 */
public def getParents(potential, f, g, local, default) {
    getParentsExtended(potential, identity, f, g, local, default)
}
```

Generally speaking, `[ ... ]` represents a tuple while `|` an "or" between possible data types (union type). As to
```
 * @return          [[num|T,T']], [[imRoot()|noParent()|f(parent), g(value)]]    // this a tuple of two tuples
```
- `[num|T,T']` a tuple with two elements:
    - a number or a value of type `T`
    - *and* a value of type `T'`. `|` has a higher priority than `,` (I hope the doc to be consistent :))
- `[[imRoot()|noParent()|f(parent), g(value)]]` a tuple with two elements:
    -  `imRoot()|noParent()|f(parent)` a value among the listed ones. Unfortunately, `imRoot()` and `noParent()` return numeric values, while `f(parent)` returns any value of type `T'`
    - *and* a value of type `T` returned by `g(local)`

**Comment by DanySK** [comment]
@metaphori, my proposal is, at the moment, to generate a Protelis Tuple argument / return type when `[]` are matched, and report the description in the text. We could also process the @see tag.
